/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorCliente;
import javax.crypto.SealedObject;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;


public class Buscar extends javax.swing.JPanel {

    
    private Cliente cliente;
     private DefaultTableModel tableModel;
    
    public Buscar() {
         this.tableModel = tableModel;
     this.setSize(757, 544);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        buscarTextField = new javax.swing.JTextField();
        RBnombre = new javax.swing.JRadioButton();
        RBcodigo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        clienteTextField = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnDepositar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        saldoTextField = new javax.swing.JTextField();
        cuentaTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        btnGuardar1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Buscar:");

        buscarTextField.setBackground(new java.awt.Color(29, 40, 81));
        buscarTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        buscarTextField.setForeground(new java.awt.Color(255, 255, 255));
        buscarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTextFieldActionPerformed(evt);
            }
        });

        RBnombre.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        RBnombre.setForeground(new java.awt.Color(255, 255, 255));
        RBnombre.setSelected(true);
        RBnombre.setText("Nombre");
        RBnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBnombreActionPerformed(evt);
            }
        });

        RBcodigo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        RBcodigo.setForeground(new java.awt.Color(255, 255, 255));
        RBcodigo.setText("ID");
        RBcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBcodigoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Cliente:");

        clienteTextField.setBackground(new java.awt.Color(29, 40, 81));
        clienteTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        clienteTextField.setForeground(new java.awt.Color(255, 255, 255));
        clienteTextField.setEnabled(false);
        clienteTextField.setOpaque(true);
        clienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTextFieldActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(29, 40, 81));
        btnEditar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnDepositar.setBackground(new java.awt.Color(51, 255, 51));
        btnDepositar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnDepositar.setForeground(new java.awt.Color(255, 255, 255));
        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnRetirar.setBackground(new java.awt.Color(102, 0, 0));
        btnRetirar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(29, 40, 81));
        btnBuscar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        saldoTextField.setBackground(new java.awt.Color(29, 40, 81));
        saldoTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        saldoTextField.setForeground(new java.awt.Color(255, 255, 255));
        saldoTextField.setEnabled(false);
        saldoTextField.setOpaque(true);
        saldoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoTextFieldActionPerformed(evt);
            }
        });

        cuentaTextField.setBackground(new java.awt.Color(29, 40, 81));
        cuentaTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cuentaTextField.setForeground(new java.awt.Color(255, 255, 255));
        cuentaTextField.setEnabled(false);
        cuentaTextField.setOpaque(true);
        cuentaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaTextFieldActionPerformed(evt);
            }
        });

        idTextField.setBackground(new java.awt.Color(29, 40, 81));
        idTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        idTextField.setForeground(new java.awt.Color(255, 255, 255));
        idTextField.setEnabled(false);
        idTextField.setOpaque(true);
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        btnGuardar1.setBackground(new java.awt.Color(29, 40, 81));
        btnGuardar1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setText("Regresar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(29, 40, 81));
        jLabel3.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                    BUSCAR CLIENTE");
        jLabel3.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Numero Cuenta:");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Numero Cliente:");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setText("Saldo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(RBnombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RBcodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDepositar))
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnEliminar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuentaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(clienteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(saldoTextField)
                    .addComponent(idTextField))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(clienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuentaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saldoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RBnombre)
                                    .addComponent(RBcodigo)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEliminar))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDepositar)
                                    .addComponent(btnRetirar)))
                            .addComponent(jLabel2))
                        .addGap(121, 121, 121)
                        .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try{
        if(RBnombre.isSelected())
           cliente = ControladorCliente.buscar(buscarTextField.getText());
        else if(RBcodigo.isSelected())
           cliente = ControladorCliente.buscar(Integer.parseInt(buscarTextField.getText()));
        else JOptionPane.showMessageDialog(this,"Seleccione un criterio de búsqueda");
        
        clienteTextField.setText(cliente.getNombre());
        saldoTextField.setText(String.format("%.2f", cliente.getSaldo()));
        cuentaTextField.setText(cliente.getNumeroCuenta());
        idTextField.setText(String.valueOf(cliente.getIdCliente()));
   
        }catch(Exception exception){
            JOptionPane.showMessageDialog(this, "Ocurrió un Error, Verifique los campos");
            }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        ClienteGUI clienteGui = new ClienteGUI(cliente);
        
        new Ventana(clienteGui);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        try{
           {
            String monto = JOptionPane.showInputDialog(this, "Ingrese el depósito");
            //  ventana empergente con la confirmación del deposito y el nuevo saldo
            JOptionPane.showMessageDialog(this, "Depósito agregado, el nuevo saldo es: " +
                            cliente.depositar(Double.parseDouble(monto)));
                    saldoTextField.setText(String.format("%.2f", cliente.getSaldo()));

                } 
           }  catch(Exception exception){
          JOptionPane.showMessageDialog(this, "Ocurrió un Error");
      }
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
     try{   
          String retiro = JOptionPane.showInputDialog(this, "Ingrese la cantidad a retirar");
          Double nuevoSaldo = cliente.retirar(Double.parseDouble(retiro));
                  saldoTextField.setText(String.format("%.2f", cliente.getSaldo()));

          if (nuevoSaldo != null) {
            JOptionPane.showMessageDialog(this, "Retiro realizado, el nuevo saldo es: " +
              nuevoSaldo);
            } else {
             JOptionPane.showMessageDialog(this, "No tiene Dinero sufiente");
            }                
        }catch(Exception exception){
          JOptionPane.showMessageDialog(this, "Ocurrió un Error");
      }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       int confrimacion = JOptionPane.showConfirmDialog(this,
                            "¿Seguro que desea borrar este cliente?", "Warning", 1);
       if (confrimacion == JOptionPane.YES_OPTION) {
             ControladorCliente.eliminar(cliente);
             JOptionPane.showMessageDialog(this, "Eliminado");
           }
                        
                        

        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void RBcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBcodigoActionPerformed
      RBnombre.setSelected(false);
    }//GEN-LAST:event_RBcodigoActionPerformed

    private void RBnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBnombreActionPerformed
      RBcodigo.setSelected(false);
    }//GEN-LAST:event_RBnombreActionPerformed

    private void clienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTextFieldActionPerformed

    private void saldoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoTextFieldActionPerformed

    private void cuentaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaTextFieldActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        Menu menu = new Menu();
        Ventana ventanaActual = (Ventana) this.getTopLevelAncestor();
        ventanaActual.setContentPane(menu);
        ventanaActual.revalidate();
        ventanaActual.repaint();
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void buscarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBcodigo;
    private javax.swing.JRadioButton RBnombre;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JTextField buscarTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField clienteTextField;
    private javax.swing.JTextField cuentaTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField saldoTextField;
    // End of variables declaration//GEN-END:variables
}
