/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorCliente;
import javax.swing.JOptionPane;
import modelo.Cliente;


public class ClienteGUI extends javax.swing.JPanel {

    
    private Cliente cliente;
   
    public ClienteGUI() {
        initComponents();
      
    }
    
    
    public ClienteGUI(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        nombreTextField.setText(cliente.getNombre());
        direccionTextField.setText(cliente.getDireccion());
        emailTextField.setText(cliente.getEmail());
        saldoTextField.setEnabled(false);
        saldoTextField.setText("" + cliente.getSaldo());
        celularTextField.setText("" + cliente.getCelular());
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        celularTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        direccionTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        saldoTextField = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(255, 255, 255));

        nombreTextField.setBackground(new java.awt.Color(29, 40, 81));
        nombreTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        nombreTextField.setForeground(new java.awt.Color(255, 255, 255));
        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 40, 81));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(29, 40, 81));
        jLabel2.setText("Dirección:");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(29, 40, 81));
        jLabel6.setText("Celular:");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 40, 81));
        jLabel3.setText("Correo:");

        celularTextField.setBackground(new java.awt.Color(29, 40, 81));
        celularTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        celularTextField.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(29, 40, 81));
        jLabel4.setText("Saldo Inicial:");

        direccionTextField.setBackground(new java.awt.Color(29, 40, 81));
        direccionTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        direccionTextField.setForeground(new java.awt.Color(255, 255, 255));

        emailTextField.setBackground(new java.awt.Color(29, 40, 81));
        emailTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        saldoTextField.setBackground(new java.awt.Color(29, 40, 81));
        saldoTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        saldoTextField.setForeground(new java.awt.Color(255, 255, 255));
        saldoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoTextFieldActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(29, 40, 81));
        btnGuardar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(29, 40, 81));
        jLabel7.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("                      AÑADIR CLIENTE");
        jLabel7.setOpaque(true);

        btnGuardar1.setBackground(new java.awt.Color(29, 40, 81));
        btnGuardar1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setText("Regresar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(201, 201, 201)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(172, 172, 172)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(celularTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celularTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void saldoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoTextFieldActionPerformed

    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(cliente == null){
            
            try{
                validaciones();
                ControladorCliente.agregar(
                    nombreTextField.getText(),
                    direccionTextField.getText(),
                    emailTextField.getText(),
                    Double.parseDouble(saldoTextField.getText()),
                    Long.parseLong(celularTextField.getText()),
                    ControladorCliente.generarNumeroCuenta());
             JOptionPane.showMessageDialog(this, "Cliente agregado, Puede agregar otro o Cerrar la ventana");
             limpiarFormulario();
            } catch(Exception exception){
            JOptionPane.showMessageDialog(this, 
                    "Ocurrió un Error, Verifique los campos: "
                    + exception.getMessage());
            }
           
        }
        else{
            try{
                validaciones();
            int idClienteLista = ControladorCliente.buscar(cliente);
            // asigna los nuevos valores al cliente
            cliente.setNombre(nombreTextField.getText());
            cliente.setDireccion(direccionTextField.getText());
            cliente.setEmail(emailTextField.getText());
            cliente.setCelular(Long.parseLong(celularTextField.getText()));
            ControladorCliente.editar(idClienteLista, cliente);
            JOptionPane.showMessageDialog(this, "Cliente Editado, puede cierre la ventana");
            }catch(Exception exception){
            JOptionPane.showMessageDialog(this, "Ocurrió un Error, Verifique los campos");
            }

            
        }            
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
    Menu menu = new Menu();
    Ventana ventanaActual = (Ventana) this.getTopLevelAncestor();
    ventanaActual.setContentPane(menu);
    ventanaActual.revalidate();
    ventanaActual.repaint();
    }//GEN-LAST:event_btnGuardar1ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JTextField celularTextField;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField saldoTextField;
    // End of variables declaration//GEN-END:variables

    private void limpiarFormulario() {
        this.cliente = null;
        nombreTextField.setText("");
        direccionTextField.setText("");
        emailTextField.setText("");
        saldoTextField.setText("");
        celularTextField.setText("");
       
    }

    private void validaciones() {
        if (!nombreTextField.getText().matches("|^[a-zA-Z]+(\\s*[a-zA-Z]*)*[a-zA-Z]+$|"))
          throw new UnsupportedOperationException("Nombre invalido, solo se aceptan letras");   
        if(
                nombreTextField.getText().equals("") || 
                emailTextField.getText().equals("") || 
                direccionTextField.getText().equals("")
                )       
          throw new UnsupportedOperationException("Campo nombre, email y dirección son requeridos");

        
    }
}
